In [1]:
import torch

In [9]:
h=3
token_len = 6
d_model = 6
dv = dk = d_model//h
input_shape = (token_len, d_model)
input = torch.rand(input_shape)
wq = []
for _ in range(h):
    wq.append(torch.rand((d_model, dk)))

WQ = torch.cat(wq, dim = 1)

results = []
for i in range(h):
    results.append(input @ wq[i])

Q = input @ WQ

results = torch.cat(results, dim=1)

print(Q)
print()
print(results)
print()
print(Q==results)

tensor([[0.8614, 0.8200, 2.1509, 1.7731, 1.9819, 2.0371],
        [0.9443, 0.9957, 2.5083, 1.7916, 2.1374, 1.7994],
        [1.2199, 1.0963, 2.3347, 1.3972, 1.5437, 0.9461],
        [0.6172, 0.5868, 1.6643, 1.3967, 1.3225, 1.3499],
        [1.1738, 1.1128, 2.6165, 2.1269, 1.9460, 1.9330],
        [1.2684, 1.3556, 2.2026, 1.2066, 1.7325, 1.3958]])

tensor([[0.8614, 0.8200, 2.1509, 1.7731, 1.9819, 2.0371],
        [0.9443, 0.9957, 2.5083, 1.7916, 2.1374, 1.7994],
        [1.2199, 1.0963, 2.3347, 1.3972, 1.5437, 0.9461],
        [0.6172, 0.5868, 1.6643, 1.3967, 1.3225, 1.3499],
        [1.1738, 1.1128, 2.6165, 2.1269, 1.9460, 1.9330],
        [1.2684, 1.3556, 2.2026, 1.2066, 1.7325, 1.3958]])

tensor([[ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True, False, False,  True,  True],
        [ True,  True,  True, False,  Tr